# Generated by Django 3.0.7 on 2020-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_stock_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Human Resource', 'Human Resource')], max_length=50, null=True),
        ),
    ]
