# Generated by Django 3.0.7 on 2020-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_stock_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='appreciation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
