# Generated by Django 3.0.7 on 2020-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_stock_appreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='months',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
