# Generated by Django 3.0.7 on 2020-10-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20201008_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='months',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='value',
        ),
        migrations.CreateModel(
            name='Depreciate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('depreciation_rate', models.PositiveIntegerField(null=True)),
                ('months', models.PositiveIntegerField(null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('appreciation_rate', models.PositiveIntegerField(null=True)),
                ('months', models.PositiveIntegerField(null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmanagement.Stock')),
            ],
        ),
    ]
