# Generated by Django 3.0.7 on 2020-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_auto_20201014_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='months',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
